# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
# on:
  # Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
          
      - name: Prepare environment
        env: 
          DEPLOY_PRIVKEY: ${{ secrets.DEPLOY_PRIVKEY }}
        run: |
          mkdir ~/.ssh
          echo $DEPLOY_PRIVKEY | base64 -d > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          echo 'Host *' >> ~/.ssh/config
          echo '    StrictHostKeyChecking no' >> ~/.ssh/config
          chmod 0600 ~/.ssh/config
          git config --global user.name "My Github Action"
          git config --global user.email "no-reply@iseki.space"
      
      # - name: Install Node
        # uses: actions/setup-node@v2-beta
        
      - name: install yarn
        uses: Borales/actions-yarn@v2.3.0 
        
      - name: Clone repo
        run: |
          cd /tmp
          git clone git@github.com:cpdyj/blog.git --depth 1
          cd blog
          git fetch origin website:website --depth 1
          ls
          echo AWSL
      - name: build
        run: |
          cd /tmp/blog
          sudo yarn global add hexo-cli
          yarn install
          hexo clean
          hexo g
          mv ./docs /tmp/
          git clean -xfd
          git switch website
          rm -rf ./docs
          mv /tmp/docs ./
          echo blog.iseki.space > docs/CNAME
          git add -A 
          git commit -am "Auto generate on Github Action at `date`"
          git push origin website
